// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: SuppressMessage("Usage", "CA2225:Operator overloads have named alternates")]
[assembly: SuppressMessage("Design", "CA1028:Enum Storage should be Int32")]
[assembly: SuppressMessage("Roslynator", "RCS1001:Add braces (when expression spans over multiple lines)")]
[assembly: SuppressMessage("Naming", "CA1711:Identifiers should not have incorrect suffix")]
[assembly: SuppressMessage("Design", "CA1008:Enums should have zero value")]
[assembly: SuppressMessage("Roslynator", "RCS1139:Add summary element to documentation comment")]
[assembly: SuppressMessage("Design", "CA1032:Implement standard exception constructors")]
[assembly: SuppressMessage("Roslynator", "RCS1194:Implement exception constructors")]
[assembly: SuppressMessage("Design", "CA1065:Do not raise exceptions in unexpected locations")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor")]
[assembly: SuppressMessage("Roslynator", "RCS1135:Declare enum member with zero value (when enum has FlagsAttribute)")]
[assembly: SuppressMessage("Security", "CA5392:Use DefaultDllImportSearchPaths attribute for P/Invokes")]
[assembly: SuppressMessage("Interoperability", "CA1401:P/Invokes should not be visible")]
[assembly: SuppressMessage("Naming", "CA1720:Identifier contains type name")]
[assembly: SuppressMessage("Design", "CA1069:Enums values should not be duplicated")]
[assembly: SuppressMessage("Style", "IDE0300:Simplify collection initialization")]
[assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization")]
[assembly: SuppressMessage("Performance", "CA1815:Override equals and operator equals on value types")]
[assembly: SuppressMessage("Design", "CA1051:Do not declare visible instance fields")]
[assembly: SuppressMessage("Design", "CA1043:Use Integral Or String Argument For Indexers")]
[assembly: SuppressMessage("Style", "IDE0305:Simplify collection initialization")]
[assembly: SuppressMessage("Roslynator", "RCS1073:Convert 'if' to 'return' statement")]
[assembly: SuppressMessage("Naming", "CA1716:Identifiers should not match keywords")]
[assembly: SuppressMessage("CodeQuality", "IDE0079:Remove unnecessary suppression")]
[assembly: SuppressMessage("Design", "CA1003:Use generic event handler instances")]
[assembly: SuppressMessage("Naming", "CA1724:Type names should not match namespaces")]
