using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Design", "CA1069:Enums values should not be duplicated")]
[assembly: SuppressMessage("Usage", "CA2225:Operator overloads have named alternates")]
[assembly: SuppressMessage("Security", "CA5392:Use DefaultDllImportSearchPaths attribute for P/Invokes")]
[assembly: SuppressMessage("Design", "CA1028:Enum Storage should be Int32")]
[assembly: SuppressMessage("Design", "CA1008:Enums should have zero value")]
[assembly: SuppressMessage("Performance", "CA1815:Override equals and operator equals on value types")]
[assembly: SuppressMessage("Design", "CA1051:Do not declare visible instance fields")]
[assembly: SuppressMessage("Design", "CA1032:Implement standard exception constructors")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods")]
[assembly: SuppressMessage("Design", "CA1065:Do not raise exceptions in unexpected locations")]
[assembly: SuppressMessage("Design", "CA1003:Use generic event handler instances")]
[assembly: SuppressMessage("Design", "CA1063:Implement IDisposable Correctly")]
[assembly: SuppressMessage("Design", "CA1043:Use Integral Or String Argument For Indexers")]
[assembly: SuppressMessage("Design", "CA1027:Mark enums with FlagsAttribute")]
[assembly: SuppressMessage("Design", "CA1040:Avoid empty interfaces")]
[assembly: SuppressMessage("Naming", "CA1724:Type names should not match namespaces")]
[assembly: SuppressMessage("Security", "CA5394:Do not use insecure randomness")]
[assembly: SuppressMessage("Interoperability", "SYSLIB1054:Use 'LibraryImportAttribute' instead of 'DllImportAttribute' to generate P/Invoke marshalling code at compile time")]
[assembly: SuppressMessage("Naming", "CA1716:Identifiers should not match keywords")]
[assembly: SuppressMessage("Design", "CA1034:Nested types should not be visible")]
[assembly: SuppressMessage("Interoperability", "SYSLIB1096:Convert to 'GeneratedComInterface'")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores")]
[assembly: SuppressMessage("Interoperability", "CA1401:P/Invokes should not be visible")]
[assembly: SuppressMessage("Naming", "CA1711:Identifiers should not have incorrect suffix")]
[assembly: SuppressMessage("Naming", "CA1720:Identifier contains type name")]
[assembly: SuppressMessage("Roslynator", "RCS1139:Add summary element to documentation comment")]
