namespace Win32
{
    public static partial class Keyboard
    {
        public static readonly Dictionary<char, VirtualKeyCode> AsciiToKey = new()
        {
            { '0', VirtualKeyCode.VK_0 },
            { '1', VirtualKeyCode.VK_1 },
            { '2', VirtualKeyCode.VK_2 },
            { '3', VirtualKeyCode.VK_3 },
            { '4', VirtualKeyCode.VK_4 },
            { '5', VirtualKeyCode.VK_5 },
            { '6', VirtualKeyCode.VK_6 },
            { '7', VirtualKeyCode.VK_7 },
            { '8', VirtualKeyCode.VK_8 },
            { '9', VirtualKeyCode.VK_9 },

            { 'A', VirtualKeyCode.VK_A },
            { 'B', VirtualKeyCode.VK_B },
            { 'C', VirtualKeyCode.VK_C },
            { 'D', VirtualKeyCode.VK_D },
            { 'E', VirtualKeyCode.VK_E },
            { 'F', VirtualKeyCode.VK_F },
            { 'G', VirtualKeyCode.VK_G },
            { 'H', VirtualKeyCode.VK_H },
            { 'I', VirtualKeyCode.VK_I },
            { 'J', VirtualKeyCode.VK_J },
            { 'K', VirtualKeyCode.VK_K },
            { 'L', VirtualKeyCode.VK_L },
            { 'M', VirtualKeyCode.VK_M },
            { 'N', VirtualKeyCode.VK_N },
            { 'O', VirtualKeyCode.VK_O },
            { 'P', VirtualKeyCode.VK_P },
            { 'Q', VirtualKeyCode.VK_Q },
            { 'R', VirtualKeyCode.VK_R },
            { 'S', VirtualKeyCode.VK_S },
            { 'T', VirtualKeyCode.VK_T },
            { 'U', VirtualKeyCode.VK_U },
            { 'V', VirtualKeyCode.VK_V },
            { 'W', VirtualKeyCode.VK_W },
            { 'X', VirtualKeyCode.VK_X },
            { 'Y', VirtualKeyCode.VK_Y },
            { 'Z', VirtualKeyCode.VK_Z },

            { 'a', VirtualKeyCode.VK_A },
            { 'b', VirtualKeyCode.VK_B },
            { 'c', VirtualKeyCode.VK_C },
            { 'd', VirtualKeyCode.VK_D },
            { 'e', VirtualKeyCode.VK_E },
            { 'f', VirtualKeyCode.VK_F },
            { 'g', VirtualKeyCode.VK_G },
            { 'h', VirtualKeyCode.VK_H },
            { 'i', VirtualKeyCode.VK_I },
            { 'j', VirtualKeyCode.VK_J },
            { 'k', VirtualKeyCode.VK_K },
            { 'l', VirtualKeyCode.VK_L },
            { 'm', VirtualKeyCode.VK_M },
            { 'n', VirtualKeyCode.VK_N },
            { 'o', VirtualKeyCode.VK_O },
            { 'p', VirtualKeyCode.VK_P },
            { 'q', VirtualKeyCode.VK_Q },
            { 'r', VirtualKeyCode.VK_R },
            { 's', VirtualKeyCode.VK_S },
            { 't', VirtualKeyCode.VK_T },
            { 'u', VirtualKeyCode.VK_U },
            { 'v', VirtualKeyCode.VK_V },
            { 'w', VirtualKeyCode.VK_W },
            { 'x', VirtualKeyCode.VK_X },
            { 'y', VirtualKeyCode.VK_Y },
            { 'z', VirtualKeyCode.VK_Z },

            { '.', VirtualKeyCode.OEM_PERIOD },
            { ',', VirtualKeyCode.OEM_COMMA },
            { '-', VirtualKeyCode.OEM_MINUS },
            { '+', VirtualKeyCode.OEM_PLUS },
            { '\r', VirtualKeyCode.RETURN },
            { '\t', VirtualKeyCode.TAB },
        };
    }
}
